require File.expand_path('../config/application', __FILE__)

UnifiedPayment::Application.load_tasks

task :test_unified_payment do 
  puts 'creating symlink for spec files...'
  system 'ln -s ../../spec'

  puts 'setting up db with migration(s)'
  system 'bundle exec rake db:setup RAILS_ENV=test'

  puts 'running specs...'
  system 'bundle exec rspec spec'

  puts 'dropping the db created for test...'
  system 'bundle exec rake db:drop'

  puts 'unlinking spec files...'
  system 'unlink spec'
end